import { ConvexClientProvider } from '@/components/ConvexClientProvider';
import JotaiProvider from '@/components/jotai-provider';
import Modals from '@/components/modal';
import { Toaster } from '@/components/ui/sonner';
import { ConvexAuthNextjsServerProvider } from '@convex-dev/auth/nextjs/server';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <ConvexAuthNextjsServerProvider>
         <html lang="en">
            <body className={inter.className}>
               <ConvexClientProvider>
                  <JotaiProvider>
                     <Modals />
                     <Toaster />
                     <NuqsAdapter>{children}</NuqsAdapter>
                  </JotaiProvider>
               </ConvexClientProvider>
            </body>
         </html>
      </ConvexAuthNextjsServerProvider>
   );
}
